title: "Perceptron.ai"
description: "Applied AI · Machine Learning · Mathematics"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown

permalink: /:year/:month/:day/:title/
collections:
  glossary:
    output: true
    permalink: /machine-learning-glossary/:path/
