title: Perceptron.ai
description: Machine Learning, Mathematics, and AI
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "dark"

markdown: kramdown
kramdown:
  math_engine: mathjax
