title: "Perceptron.ai"
description: "Applied AI · Machine Learning · Mathematics"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown

paginate: 5
paginate_path: /page:num/

permalink: /:year/:month/:day/:title/
